---
# 1. 创建 PersistentVolume (PV) - 存储 Nexus 数据
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-data-pv
  labels:
    app: nexus
    type: data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/nexus/data
    type: DirectoryOrCreate

---
# 2. 创建 PersistentVolume (PV) - 存储日志
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-logs-pv
  labels:
    app: nexus
    type: logs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/nexus/logs
    type: DirectoryOrCreate

---
# 3. 创建 PersistentVolumeClaim (PVC) - Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app: nexus
      type: data

---
# 4. 创建 PersistentVolumeClaim (PVC) - Logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-logs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: nexus
      type: logs

---
# 5. 创建 ConfigMap (Nexus 配置)
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-config
  namespace: default
data:
  nexus.properties: |
    # Nexus 应用配置
    application-port=8081
    application-host=0.0.0.0
    nexus-context-path=/
    
    # 数据目录
    nexus-work=/nexus-data
    
    # 性能优化
    nexus.clustered=false
    nexus.loadAsOSS=true
  
  nexus.vmoptions: |
    -Xms2048m
    -Xmx2048m
    -XX:MaxDirectMemorySize=2048m
    -XX:+UnlockDiagnosticVMOptions
    -XX:+LogVMOutput
    -XX:LogFile=/nexus-data/log/jvm.log
    -XX:-OmitStackTraceInFastThrow
    -Djava.net.preferIPv4Stack=true
    -Dkaraf.home=.
    -Dkaraf.base=.
    -Dkaraf.etc=etc/karaf
    -Djava.util.logging.config.file=etc/karaf/java.util.logging.properties
    -Dkaraf.data=/nexus-data
    -Dkaraf.log=/nexus-data/log
    -Djava.io.tmpdir=/nexus-data/tmp

---
# 6. 创建 Job - 初始化 Nexus 数据目录
apiVersion: batch/v1
kind: Job
metadata:
  name: nexus-init-data
  namespace: default
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init
        image: busybox:1.36
        command: ['sh', '-c']
        args:
          - |
            echo "开始初始化 Nexus 数据目录..."
            
            # 创建必要的目录结构
            mkdir -p /nexus-data/etc
            mkdir -p /nexus-data/log
            mkdir -p /nexus-data/tmp
            mkdir -p /nexus-data/keystores
            mkdir -p /nexus-data/cache
            mkdir -p /nexus-data/db
            mkdir -p /nexus-data/blobs
            
            # 设置权限 (Nexus 使用 UID 200)
            chown -R 200:200 /nexus-data
            chmod -R 755 /nexus-data
            
            echo "✓ Nexus 数据目录初始化完成"
            
            ls -lh /nexus-data/
        volumeMounts:
        - name: data
          mountPath: /nexus-data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nexus-data-pvc

---
# 7. 创建 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: default
  labels:
    app: nexus
spec:
  replicas: 1  # Nexus 通常运行单实例
  strategy:
    type: Recreate  # Nexus 不支持滚动更新，使用重建策略
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        fsGroup: 200  # Nexus 用户组
      containers:
      - name: nexus
        image: sonatype/nexus3:3.68.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8082
          name: docker-hosted
          protocol: TCP
        - containerPort: 8083
          name: docker-proxy
          protocol: TCP
        env:
        - name: INSTALL4J_ADD_VM_PARAMS
          value: "-Xms2048m -Xmx2048m -XX:MaxDirectMemorySize=2048m"
        - name: NEXUS_SECURITY_RANDOMPASSWORD
          value: "false"  # 生产环境建议设为 true
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
        - name: nexus-logs
          mountPath: /nexus-data/log
        - name: nexus-config
          mountPath: /opt/sonatype/nexus/etc/nexus-default.properties
          subPath: nexus.properties
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 180  # Nexus 启动较慢
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-data-pvc
      - name: nexus-logs
        persistentVolumeClaim:
          claimName: nexus-logs-pvc
      - name: nexus-config
        configMap:
          name: nexus-config

---
# 8. 创建 Service (ClusterIP - 集群内访问)
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: default
  labels:
    app: nexus
spec:
  selector:
    app: nexus
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: docker-hosted
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: docker-proxy

---
# 9. 创建 Service (NodePort - 外部访问)
apiVersion: v1
kind: Service
metadata:
  name: nexus-service-nodeport
  namespace: default
  labels:
    app: nexus
spec:
  selector:
    app: nexus
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
    protocol: TCP
    name: http
  - port: 8082
    targetPort: 8082
    nodePort: 30082
    protocol: TCP
    name: docker-hosted
  - port: 8083
    targetPort: 8083
    nodePort: 30083
    protocol: TCP
    name: docker-proxy

---
# 10. 创建 Ingress (可选 - 用于域名访问)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"  # 允许大文件上传
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
  - host: nexus.example.com  # 修改为你的域名
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexus-service
            port:
              number: 8081
  # tls:  # 可选 - 启用 HTTPS
  # - hosts:
  #   - nexus.example.com
  #   secretName: nexus-tls-secret