---
# 1. PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-data-pv
  labels:
    app: consul
    type: data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/consul/data
    type: DirectoryOrCreate

---
# 2. PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: consul
      type: data

---
# 3. 创建 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: default
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul:1.15.4
        command:
        - consul
        args:
        - agent
        - -dev
        - -ui
        - -client
        - 0.0.0.0
        ports:
        - containerPort: 8300
          name: server
          protocol: TCP
        - containerPort: 8301
          name: serf-lan
          protocol: TCP
        - containerPort: 8302
          name: serf-wan
          protocol: TCP
        - containerPort: 8500
          name: http
          protocol: TCP
        - containerPort: 8600
          name: dns
          protocol: UDP
        volumeMounts:
        - name: data
          mountPath: /consul/data
        livenessProbe:
          exec:
            command:
            - consul
            - info
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: consul-data-pvc  # 改为使用 PVC，而不是 hostPath
---
# 4. 创建 Service (NodePort - 外部访问)
apiVersion: v1
kind: Service
metadata:
  name: consul-service
  namespace: default
  labels:
    app: consul
spec:
  selector:
    app: consul
  type: NodePort
  ports:
  - port: 8300
    targetPort: 8300
    nodePort: 30000  # 改为 30000-32767 范围内
    name: server
  - port: 8301
    targetPort: 8301
    nodePort: 30001  # 改为 30000-32767 范围内
    name: serf-lan
  - port: 8302
    targetPort: 8302
    nodePort: 30002  # 改为 30000-32767 范围内
    name: serf-wan
  - port: 8500
    targetPort: 8500
    nodePort: 30003  # 改为 30000-32767 范围内
    name: http
  - port: 8600
    targetPort: 8600
    nodePort: 30004  # 改为 30000-32767 范围内
    name: dns
    protocol: UDP