---
# 1. 创建 PersistentVolume (PV) - GitLab 配置
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-config-pv
  labels:
    app: gitlab
    type: config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/gitlab/config
    type: DirectoryOrCreate

---
# 2. 创建 PersistentVolume (PV) - GitLab 日志
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs-pv
  labels:
    app: gitlab
    type: logs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/gitlab/logs
    type: DirectoryOrCreate

---
# 3. 创建 PersistentVolume (PV) - GitLab 数据
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data-pv
  labels:
    app: gitlab
    type: data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/gitlab/data
    type: DirectoryOrCreate

---
# 4. 创建 PersistentVolumeClaim (PVC) - Config
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: gitlab
      type: config

---
# 5. 创建 PersistentVolumeClaim (PVC) - Logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: gitlab
      type: logs

---
# 6. 创建 PersistentVolumeClaim (PVC) - Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: gitlab
      type: data

---
# 7. 创建 ConfigMap (GitLab 配置)
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: default
data:
  GITLAB_OMNIBUS_CONFIG: |
    external_url 'http://gitlab.local'

    # 设置初始 root 密码（必须至少8个字符）
    gitlab_rails['initial_root_password'] = ENV['GITLAB_INITIAL_ROOT_PASSWORD']
    gitlab_rails['gitlab_email_from'] = ENV['GITLAB_ROOT_EMAIL']
    
    # 关闭不必要的服务以节省资源
    prometheus_monitoring['enable'] = false
    alertmanager['enable'] = false
    grafana['enable'] = false
    gitlab_exporter['enable'] = false
    
    # GitLab 配置
    gitlab_rails['time_zone'] = 'Asia/Shanghai'
    gitlab_rails['gitlab_email_enabled'] = false
    gitlab_rails['gitlab_default_theme'] = 2
    
    # 性能优化
    puma['worker_processes'] = 2
    sidekiq['max_concurrency'] = 10
    
    # 数据库连接池
    gitlab_rails['db_pool'] = 10
    
    # Git 配置
    gitlab_rails['gitlab_shell_ssh_port'] = 2222

---
# 8. 创建 Secret
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  namespace: default
type: Opaque
stringData:
  GITLAB_ROOT_PASSWORD: gitlab123456
  GITLAB_ROOT_EMAIL: admin@gitlab.local

---
# 9. 创建 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: default
  labels:
    app: gitlab
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      securityContext:
        fsGroup: 998 # 确保卷可被 GID 998 访问
        runAsUser: 0 # 确保以 root 启动
        runAsGroup: 0 # 确保以 root 组启动 
      hostname: gitlab
      initContainers:
      - name: fix-permissions
        image: busybox
        command: 
        - sh
        - -c
        - |
          # 递归设置所有权限为 777（仅用于测试）
          chmod -R 777 /etc/gitlab /var/log/gitlab /var/opt/gitlab
          echo "权限设置为 777"
        # ---- 必须挂载卷，否则无法对宿主目录修改权限 ----
        volumeMounts:
        - name: gitlab-config
          mountPath: /etc/gitlab
        - name: gitlab-logs
          mountPath: /var/log/gitlab
        - name: gitlab-data
          mountPath: /var/opt/gitlab
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:16.11.1-ce.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 2222
          name: ssh
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: gitlab-config
              key: GITLAB_OMNIBUS_CONFIG
        # 把 Secret 的值注入为对应的 ENV（ConfigMap 中使用的是 GITLAB_INITIAL_ROOT_PASSWORD / GITLAB_ROOT_EMAIL）
        - name: GITLAB_INITIAL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: GITLAB_ROOT_PASSWORD   # <-- Secret 中原来是 GITLAB_ROOT_PASSWORD
        - name: GITLAB_ROOT_EMAIL
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: GITLAB_ROOT_EMAIL

        volumeMounts:
        - name: gitlab-config
          mountPath: /etc/gitlab
        - name: gitlab-logs
          mountPath: /var/log/gitlab
        - name: gitlab-data
          mountPath: /var/opt/gitlab
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        livenessProbe:
          httpGet:
            path: /health?target=liveness
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health?target=readiness
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: gitlab-config
        persistentVolumeClaim:
          claimName: gitlab-config-pvc
      - name: gitlab-logs
        persistentVolumeClaim:
          claimName: gitlab-logs-pvc
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-data-pvc

---
# 10. 创建 Service (ClusterIP - 集群内访问)
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: default
  labels:
    app: gitlab
spec:
  selector:
    app: gitlab
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 2222
    targetPort: 2222
    protocol: TCP
    name: ssh

---
# 11. 创建 Service (NodePort - 外部访问)
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service-nodeport
  namespace: default
  labels:
    app: gitlab
spec:
  selector:
    app: gitlab
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30088
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    nodePort: 30443
    protocol: TCP
    name: https
  - port: 2222
    targetPort: 2222
    nodePort: 30222
    protocol: TCP
    name: ssh