---
# 1. 创建 PersistentVolume (PV)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app: redis
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/redis/data
    type: DirectoryOrCreate

---
# 2. 创建 PersistentVolumeClaim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: redis

---
# 3. 创建 ConfigMap (Redis 配置文件)
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: default
data:
  redis.conf: |
    # Redis 配置文件
    bind 0.0.0.0
    port 6379
    
    # 持久化配置
    save 900 1
    save 300 10
    save 60 10000
    
    # AOF 持久化
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    
    # 内存管理
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    
    # 日志
    loglevel notice
    
    # 其他配置
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    
    # 禁用危险命令
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command KEYS ""

---
# 4. 创建 Secret (Redis 密码)
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: default
type: Opaque
stringData:
  REDIS_PASSWORD: redis123456

---
# 5. 创建 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2-alpine
        imagePullPolicy: IfNotPresent
        command:
          - redis-server
          - /usr/local/etc/redis/redis.conf
          - --requirepass
          - $(REDIS_PASSWORD)
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        - name: redis-config
          mountPath: /usr/local/etc/redis
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
              - redis-cli
              - -a
              - $(REDIS_PASSWORD)
              - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - redis-cli
              - -a
              - $(REDIS_PASSWORD)
              - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
      - name: redis-config
        configMap:
          name: redis-config
          items:
          - key: redis.conf
            path: redis.conf

---
# 6. 创建 Service (ClusterIP - 集群内访问)
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
  labels:
    app: redis
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis

---
# 7. 创建 Service (NodePort - 外部访问)
apiVersion: v1
kind: Service
metadata:
  name: redis-service-nodeport
  namespace: default
  labels:
    app: redis
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30379
    protocol: TCP
    name: redis