---
# 1. 创建 PersistentVolume (PV) - 存储静态文件
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-html-pv
  labels:
    app: nginx
    type: html
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/nginx/html
    type: DirectoryOrCreate

---
# 2. 创建 PersistentVolume (PV) - 存储日志
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-logs-pv
  labels:
    app: nginx
    type: logs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/nginx/logs
    type: DirectoryOrCreate

---
# 3. 创建 PersistentVolumeClaim (PVC) - HTML
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-html-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: nginx
      type: html

---
# 4. 创建 PersistentVolumeClaim (PVC) - Logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-logs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: nginx
      type: logs

---
# 5. 创建 ConfigMap (Nginx 配置)
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;
    
    events {
        worker_connections 1024;
        use epoll;
    }
    
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
        
        access_log /var/log/nginx/access.log main;
        
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        client_max_body_size 20M;
        
        # Gzip 压缩
        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css text/xml text/javascript 
                   application/json application/javascript application/xml+rss 
                   application/rss+xml font/truetype font/opentype 
                   application/vnd.ms-fontobject image/svg+xml;
        
        # 包含虚拟主机配置
        include /etc/nginx/conf.d/*.conf;
    }
  
  default.conf: |
    server {
        listen 80;
        server_name _;
        
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # 访问日志
        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log warn;
        
        # 主页
        location / {
            try_files $uri $uri/ /index.html;
        }
        
        # 健康检查端点
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
        
        # 状态页面
        location /nginx_status {
            stub_status on;
            access_log off;
            allow 127.0.0.1;
            allow 10.0.0.0/8;
            deny all;
        }
        
        # 静态资源缓存
        location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
            expires 30d;
            add_header Cache-Control "public, immutable";
        }
        
        # 安全头
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        
        # 禁止访问隐藏文件
        location ~ /\. {
            deny all;
            access_log off;
            log_not_found off;
        }
    }
  
---
# 6. 创建 Job - 初始化 HTML 文件
apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-init-html
  namespace: default
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init
        image: busybox:1.36
        command: ['sh', '-c']
        args:
          - |
            echo "开始初始化 HTML 文件..."
            
            if [ ! -f /html/index.html ]; then
              cat > /html/index.html << 'EOF'
            <!DOCTYPE html>
            <html lang="zh-CN">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Nginx on Kubernetes</title>
                <style>
                    * { margin: 0; padding: 0; box-sizing: border-box; }
                    body {
                        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
                        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                        min-height: 100vh;
                        display: flex;
                        align-items: center;
                        justify-content: center;
                        padding: 20px;
                    }
                    .container {
                        background: white;
                        border-radius: 20px;
                        padding: 60px 40px;
                        box-shadow: 0 20px 60px rgba(0,0,0,0.3);
                        text-align: center;
                        max-width: 600px;
                        width: 100%;
                        animation: fadeIn 0.5s ease-in;
                    }
                    @keyframes fadeIn {
                        from { opacity: 0; transform: translateY(20px); }
                        to { opacity: 1; transform: translateY(0); }
                    }
                    h1 {
                        color: #333;
                        font-size: 2.5em;
                        margin-bottom: 20px;
                    }
                    .logo {
                        font-size: 80px;
                        margin-bottom: 20px;
                        animation: bounce 2s infinite;
                    }
                    @keyframes bounce {
                        0%, 100% { transform: translateY(0); }
                        50% { transform: translateY(-10px); }
                    }
                    p {
                        color: #666;
                        font-size: 1.2em;
                        line-height: 1.6;
                        margin-bottom: 30px;
                    }
                    .info {
                        background: #f8f9fa;
                        border-radius: 10px;
                        padding: 20px;
                        margin-top: 30px;
                    }
                    .info-item {
                        display: flex;
                        justify-content: space-between;
                        padding: 10px 0;
                        border-bottom: 1px solid #e0e0e0;
                    }
                    .info-item:last-child { border-bottom: none; }
                    .label {
                        font-weight: 600;
                        color: #555;
                    }
                    .value {
                        color: #667eea;
                        font-family: monospace;
                    }
                    .btn {
                        display: inline-block;
                        padding: 12px 30px;
                        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                        color: white;
                        text-decoration: none;
                        border-radius: 25px;
                        margin: 10px;
                        transition: all 0.3s;
                        border: none;
                        cursor: pointer;
                        font-size: 16px;
                    }
                    .btn:hover {
                        transform: translateY(-2px);
                        box-shadow: 0 5px 15px rgba(102, 126, 234, 0.4);
                    }
                    .status {
                        display: inline-block;
                        width: 10px;
                        height: 10px;
                        background: #4caf50;
                        border-radius: 50%;
                        margin-right: 5px;
                        animation: pulse 2s infinite;
                    }
                    @keyframes pulse {
                        0%, 100% { opacity: 1; }
                        50% { opacity: 0.5; }
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="logo">🚀</div>
                    <h1>Nginx on Kubernetes</h1>
                    <p>您的 Nginx 服务器已在 Kubernetes 集群中成功运行！</p>
                    <p>数据持久化存储在 PV/PVC 中</p>
                    
                    <div class="info">
                        <div class="info-item">
                            <span class="label">服务器</span>
                            <span class="value">Nginx 1.25</span>
                        </div>
                        <div class="info-item">
                            <span class="label">平台</span>
                            <span class="value">Kubernetes</span>
                        </div>
                        <div class="info-item">
                            <span class="label">存储</span>
                            <span class="value">PV/PVC</span>
                        </div>
                        <div class="info-item">
                            <span class="label">状态</span>
                            <span class="value"><span class="status"></span>Running</span>
                        </div>
                        <div class="info-item">
                            <span class="label">时间</span>
                            <span class="value" id="time">--:--:--</span>
                        </div>
                    </div>
                    
                    <div style="margin-top: 20px;">
                        <a href="/health" class="btn">健康检查</a>
                        <button class="btn" onclick="testAPI()">测试 API</button>
                    </div>
                </div>
                
                <script>
                    function updateTime() {
                        const now = new Date();
                        document.getElementById('time').textContent = now.toLocaleTimeString('zh-CN');
                    }
                    setInterval(updateTime, 1000);
                    updateTime();
                    
                    function testAPI() {
                        fetch('/health')
                            .then(response => response.text())
                            .then(data => {
                                alert('健康检查成功！\n响应: ' + data);
                            })
                            .catch(error => {
                                alert('健康检查失败: ' + error);
                            });
                    }
                </script>
            </body>
            </html>
            EOF
              echo "✓ HTML 文件创建完成"
            else
              echo "HTML 文件已存在，跳过创建"
            fi
            
            ls -lh /html/
        volumeMounts:
        - name: html
          mountPath: /html
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: nginx-html-pvc
  

---
# 7. 创建 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: nginx-html
          mountPath: /usr/share/nginx/html
        - name: nginx-logs
          mountPath: /var/log/nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-html
        persistentVolumeClaim:
          claimName: nginx-html-pvc
      - name: nginx-logs
        persistentVolumeClaim:
          claimName: nginx-logs-pvc

---
# 8. 创建 Service (ClusterIP - 集群内访问)
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http

---
# 9. 创建 Service (NodePort - 外部访问)
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
  namespace: default
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http