# 2. 创建 Persistent Volume Claim (PVC) 存储声明
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc # PVC 名称
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual    
  resources:
    requests:
      storage: 10Gi
  
  selector:
    matchLabels:
      app: mysql
      