# 6. 创建 Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  # type: ClusterIP
  type: NodePort # ✅ 改这里
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30032 # ✅ 固定一个端口（范围 30000-32767）
      protocol: TCP
      name: postgres
