---
# 1. 创建 PersistentVolume (PV) - Node 1 数据
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv-1
  labels:
    app: elasticsearch
    type: data
    node: "1"
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/elasticsearch/data-1
    type: DirectoryOrCreate

---
# 2. 创建 PersistentVolume (PV) - Node 2 数据
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv-2
  labels:
    app: elasticsearch
    type: data
    node: "2"
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/elasticsearch/data-2
    type: DirectoryOrCreate

---
# 3. 创建 PersistentVolume (PV) - Node 3 数据
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv-3
  labels:
    app: elasticsearch
    type: data
    node: "3"
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/elasticsearch/data-3
    type: DirectoryOrCreate

---
# 4. 创建 PersistentVolume (PV) - 日志存储
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-logs-pv
  labels:
    app: elasticsearch
    type: logs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/elasticsearch/logs
    type: DirectoryOrCreate

---
# 5. 创建 ConfigMap (Elasticsearch 配置)
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: default
data:
  elasticsearch.yml: |
    # 集群配置
    cluster.name: es-cluster
    network.host: 0.0.0.0
    
    # 发现配置
    discovery.seed_hosts:
      - elasticsearch-0.elasticsearch-headless
      - elasticsearch-1.elasticsearch-headless
      - elasticsearch-2.elasticsearch-headless
    cluster.initial_master_nodes:
      - elasticsearch-0
      - elasticsearch-1
      - elasticsearch-2
    
    # 节点配置
    node.master: true
    node.data: true
    node.ingest: true
    
    # 路径配置
    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs
    
    # 内存配置
    bootstrap.memory_lock: false
    
    # 网络配置
    http.port: 9200
    transport.port: 9300
    
    # 安全配置 (开发环境)
    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false
    
    # 监控配置
    xpack.monitoring.collection.enabled: true
    
    # 跨域配置
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    http.cors.allow-headers: "X-Requested-With,Content-Type,Content-Length,Authorization"
  
  jvm.options: |
    ## JVM 配置
    
    # Xms 和 Xmx 设置为相同值
    -Xms1g
    -Xmx1g
    
    # GC 配置
    -XX:+UseG1GC
    -XX:G1ReservePercent=25
    -XX:InitiatingHeapOccupancyPercent=30
    
    # DNS 缓存配置
    -Des.networkaddress.cache.ttl=60
    -Des.networkaddress.cache.negative.ttl=10
    
    # 性能优化
    -XX:+AlwaysPreTouch
    -Xss1m
    -Djava.awt.headless=true
    -Dfile.encoding=UTF-8
    -Djna.nosys=true
    -XX:-OmitStackTraceInFastThrow
    -Dio.netty.noUnsafe=true
    -Dio.netty.noKeySetOptimization=true
    -Dio.netty.recycler.maxCapacityPerThread=0
    -Dlog4j.shutdownHookEnabled=false
    -Dlog4j2.disable.jmx=true
    
    # GC 日志
    -Xlog:gc*,gc+age=trace,safepoint:file=/usr/share/elasticsearch/logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m

---
# 6. 创建 Job - 初始化目录权限
apiVersion: batch/v1
kind: Job
metadata:
  name: es-init-permissions
  namespace: default
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init
        image: busybox:1.36
        command: ['sh', '-c']
        args:
          - |
            echo "开始初始化 Elasticsearch 数据目录..."
            
            # 为每个节点创建目录
            for i in 1 2 3; do
              mkdir -p /data/data-$i
              mkdir -p /data/data-$i/nodes
              chmod -R 777 /data/data-$i
              echo "✓ 节点 $i 数据目录初始化完成"
            done
            
            # 创建日志目录
            mkdir -p /logs
            chmod -R 777 /logs
            echo "✓ 日志目录初始化完成"
            
            echo "所有目录初始化完成"
        volumeMounts:
        - name: data
          mountPath: /data
        - name: logs
          mountPath: /logs
      volumes:
      - name: data
        hostPath:
          path: /mnt/host/d/dockerstore/elasticsearch
          type: DirectoryOrCreate
      - name: logs
        persistentVolumeClaim:
          claimName: es-logs-pvc

---
# 7. 创建 PersistentVolumeClaim (PVC) - Logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-logs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: elasticsearch
      type: logs

---
# 8. 创建 Headless Service (用于集群发现)
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  namespace: default
  labels:
    app: elasticsearch
spec:
  clusterIP: None  # Headless Service
  selector:
    app: elasticsearch
  ports:
  - port: 9300
    name: transport
    protocol: TCP

---
# 9. 创建 StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: default
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch-headless
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      # 设置系统参数
      - name: sysctl
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          sysctl -w vm.max_map_count=262144
          ulimit -n 65536
        securityContext:
          privileged: true
      
      # 修复权限
      - name: fix-permissions
        image: busybox:1.36
        command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      
      containers:
      - name: elasticsearch
        image: elasticsearch:8.11.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: ELASTIC_PASSWORD
          value: "elastic123"  # 生产环境请使用 Secret
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: logs
          mountPath: /usr/share/elasticsearch/logs
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: config
          mountPath: /usr/share/elasticsearch/config/jvm.options
          subPath: jvm.options
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /_cluster/health?wait_for_status=yellow&timeout=5s
            port: 9200
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: es-logs-pvc
      - name: config
        configMap:
          name: es-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: manual
      resources:
        requests:
          storage: 30Gi
      selector:
        matchLabels:
          app: elasticsearch
          type: data

---
# 10. 创建 Service (ClusterIP - 集群内访问)
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: default
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: http
  - port: 9300
    targetPort: 9300
    protocol: TCP
    name: transport

---
# 11. 创建 Service (NodePort - 外部访问)
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-nodeport
  namespace: default
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30920
    protocol: TCP
    name: http

---
# 12. 创建 Ingress (可选 - 用于域名访问)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
  - host: es.example.com  # 修改为你的域名
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elasticsearch-service
            port:
              number: 9200