---
# 1. 创建 PersistentVolume (PV) - Jenkins 配置
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-config-pv
  labels:
    app: jenkins
    type: config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/jenkins/config
    type: DirectoryOrCreate

---
# 2. 创建 PersistentVolume (PV) - Jenkins 日志
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-logs-pv
  labels:
    app: jenkins
    type: logs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/jenkins/logs
    type: DirectoryOrCreate

---
# 3. 创建 PersistentVolume (PV) - Jenkins 数据
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-data-pv
  labels:
    app: jenkins
    type: data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/host/d/dockerstore/jenkins/data
    type: DirectoryOrCreate

---
# 4. 创建 PersistentVolumeClaim (PVC) - Config
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: jenkins
      type: config

---
# 5. 创建 PersistentVolumeClaim (PVC) - Logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-logs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: jenkins
      type: logs

---
# 6. 创建 PersistentVolumeClaim (PVC) - Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: jenkins
      type: data

---
# 7. 创建 ConfigMap (Jenkins 配置)
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: default
data:
  JENKINS_OPTS: |
    --httpPort=8080
    --webroot=/var/cache/jenkins/war
    --prefix=/jenkins
    
  JENKINS_JAVA_OPTS: |
    -Djava.awt.headless=true
    -Djenkins.install.runSetupWizard=false
    -Dhudson.model.DirectoryBrowserSupport.CSP=""
    -Xmx2g
    -Xms512m
    -XX:MaxMetaspaceSize=512m
    -XX:MetaspaceSize=256m
    -Duser.timezone=Asia/Shanghai

---
# 8. 创建 Secret
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: default
type: Opaque
stringData:
  JENKINS_ADMIN_USER: admin
  JENKINS_ADMIN_PASSWORD: jenkins123456

---
# 9. 创建 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: default
  labels:
    app: jenkins
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0
        runAsGroup: 0
      hostname: jenkins
      initContainers:
      - name: fix-permissions
        image: busybox
        command: 
        - sh
        - -c
        - |
          echo "设置 Jenkins 目录权限..."
          chown -R 1000:1000 /var/jenkins_home
          chmod -R 755 /var/jenkins_home
          chown -R 1000:1000 /var/log/jenkins
          chmod -R 755 /var/log/jenkins
          echo "权限设置完成"
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
        - name: jenkins-logs
          mountPath: /var/log/jenkins
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.446-jdk17
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50000
          name: jnlp
        env:
        - name: JENKINS_OPTS
          valueFrom:
            configMapKeyRef:
              name: jenkins-config
              key: JENKINS_OPTS
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: jenkins-config
              key: JENKINS_JAVA_OPTS
        - name: JENKINS_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: jenkins-secret
              key: JENKINS_ADMIN_USER
        - name: JENKINS_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jenkins-secret
              key: JENKINS_ADMIN_PASSWORD
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
        - name: jenkins-logs
          mountPath: /var/log/jenkins
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /jenkins/login
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /jenkins/login
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-data-pvc
      - name: jenkins-logs
        persistentVolumeClaim:
          claimName: jenkins-logs-pvc

---
# 10. 创建 Service (ClusterIP - 集群内访问)
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: default
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 50000
    targetPort: 50000
    protocol: TCP
    name: jnlp

---
# 11. 创建 Service (NodePort - 外部访问)
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service-nodeport
  namespace: default
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30090
    protocol: TCP
    name: http
  - port: 50000
    targetPort: 50000
    nodePort: 30091
    protocol: TCP
    name: jnlp