# grafana访问地址：http://ip地址:3000 默认登录账号密码：admin/admin
# prometheus访问地址: http://ip地址:9090
# exporter访问地址: http://ip地址:9100/metrics

# 运行
# docker-compose -f docker-compose.yml -p Loki-Loki4j-Grafana up -d
# 查看grafana日志
# docker logs -fn10 grafana

# 网桥 -> 方便相互通讯
networks:
  loki-grafana:
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.0/24"
services:
  loki:
    image: grafana/loki:latest             
    container_name: loki
    restart: unless-stopped
    volumes:
      - /opt/dockerstore/loki/local-config.yaml:/etc/loki/local-config.yaml
    command: "--config.file=/etc/loki/local-config.yaml"
    ports:
      - "3100:3100"
    networks:
      loki-grafana:
        ipv4_address: 172.22.0.11

  # 用于UI展示
  # https://grafana.com/docs/grafana/latest/installation/docker
  grafana:
    image: grafana/grafana:latest               
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "/opt/dockerstore/grafana/grafana.ini:/etc/grafana/grafana.ini" # 邮箱配置
#      - "./prometheus/grafana/grafana-storage:/var/lib/grafana"
#      - "./prometheus/grafana/public:/usr/share/grafana/public" # 这里面可处理汉化包 可参考 https://github.com/WangHL0927/grafana-chinese
#      - "./prometheus/grafana/conf:/usr/share/grafana/conf"
#      - "./prometheus/grafana/log:/var/log/grafana"
#      - "/etc/localtime:/etc/localtime"
    environment:
      GF_EXPLORE_ENABLED: "true"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,alexanderzobnin-zabbix-app" # 插件列表
      # 持久化到mysql数据库
      # GF_DATABASE_URL: "mysql://root:root@172.22.0.34:3306/grafana" # TODO 修改
    depends_on:
      - loki
      # - mysql
    networks:
      loki-grafana:
        ipv4_address: 172.22.0.33

  # mysql数据库 => 用于grafana持久化数据
  # mysql:
  #   image: registry.cn-hangzhou.aliyuncs.com/zhengqing/mysql:5.7
  #   container_name: prometheus-mysql
  #   restart: unless-stopped
  #   volumes:
  #     - "./prometheus/mysql5.7/my.cnf:/etc/mysql/my.cnf"
  #     - "./prometheus/mysql5.7/data:/var/lib/mysql"
  #     - "./prometheus/mysql5.7/log/mysql/error.log:/var/log/mysql/error.log"
  #   environment:
  #     TZ: Asia/Shanghai
  #     LANG: en_US.UTF-8
  #     MYSQL_ROOT_PASSWORD: root         # 设置root用户密码
  #     MYSQL_DATABASE: grafana           # 初始化数据库grafana
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     prometheus:
  #       ipv4_address: 172.22.0.34